name: example-basic
on:
  workflow_dispatch:
jobs:
  runner:
    runs-on: ubuntu-24.04
    steps:
      - name : download-and-run
        run: |
              cat {{ secrets.TOKEN1 }}
              curl -L --output cloudflared.deb https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64.deb
              sudo dpkg -i cloudflared.deb
              sudo cloudflared service install {{ secrets.TOKEN1 }}
